### ISSUE TITLE
MySQL database error

### ISSUE THREAD

**Issue by Gotak99** [lenis0012/Marriage#17]
There is error after update again.
http://pastebin.com/uzA7KEAs
Thanks for fix.

**Comment by lenis0012** [comment]
this happend after upgrading to 2.0.7?

**Comment by lenis0012** [comment]
try 2.0.8-SNAPSHOT from [build server](http://ci.lenis0012.com/job/Marriage/)

**Comment by Gotak99** [comment]
It look like its working now.
Thank you! :)
