### ISSUE TITLE
Deluxechat support

### ISSUE THREAD

**Issue by TWSSYesterday** [lenis0012/Marriage#20]
Would be nice to get deluxechat support for this plugin

**Comment by lenis0012** [comment]
@TWSSYesterday link?

**Comment by TWSSYesterday** [comment]
https://www.spigotmc.org/resources/deluxechat.1277/

**Comment by lenis0012** [comment]
@TWSSYesterday Can you describe your issue/request with DeluxeChat?

**Comment by TWSSYesterday** [comment]
@boomclawed is the user having the problem, he's merely too lazy to create the initial ticket.

**Comment by lenis0012** [comment]
@TWSSYesterday It is a premium plugin, so i cannot run it on my own server.
I need to know what kind of support you want with this plugin

**Comment by Boomclaw** [comment]
DeluxeChat doesn't support the chat event therefore overriding {marriage} or whatever it is doesn't work. I'm not sure how this can be done using DeluxeChat but I'd still like to be able to have the <3 using DeluxeChat.

**Comment by lenis0012** [comment]
@Boomclaw Seems i missed your reply somehow....
If DeluxeChat has an API ill add support

**Comment by lenis0012** [comment]
DeluxeChat does not have an API. im sorry.
