### ISSUE TITLE
1.12 Incompatibility

### ISSUE THREAD

**Issue by Skegnas** [lenis0012/Marriage#30]
Whenever doing a command in 1.12 you get an error like the one linked below. I know there's a fork with a fix for the incompatibility but was wondering if it was possible to have a fill 1.12-compatible release? :-)

https://pastebin.com/sqcbD4L6

**Comment by lenis0012** [comment]
@Skegnas I will release an update tonight and make sure to resolve the issue.

I initially swapped the spigot version and checked if the plugin enabled without any errors.
I didn't go any further in terms of 1.12 testing.

**Comment by Skegnas** [comment]
Awesome, thanks!
