### ISSUE TITLE
Changing messages in the messages.yml

### ISSUE THREAD

**Issue by SirCLASH** [lenis0012/Marriage#32]
After changing the messages in the messages.yml-File i got errors, when trying to use the most /marry commands. I changed the config from UTF-8 without BOM to UTF-8 to use german characters like ä, ö and ü.

15.08 16:14:03 [Server] INFO ... 15 more
15.08 16:14:03 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
15.08 16:14:03 [Server] INFO at com.lenis0012.bukkit.marriage2.internal.MarriageCommandExecutor.onCommand(MarriageCommandExecutor.java:37) ~[?:?]
15.08 16:14:03 [Server] INFO at com.lenis0012.bukkit.marriage2.commands.CommandMarry.execute(CommandMarry.java:34) ~[?:?]
15.08 16:14:03 [Server] INFO at com.lenis0012.bukkit.marriage2.commands.Command.getArgAsPlayer(Command.java:55) ~[?:?]
15.08 16:14:03 [Server] INFO at com.lenis0012.bukkit.marriage2.commands.Command.getArg(Command.java:47) ~[?:?]
15.08 16:14:03 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
15.08 16:14:03 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
15.08 16:14:03 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
15.08 16:14:03 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
15.08 16:14:03 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
15.08 16:14:03 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
15.08 16:14:03 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
15.08 16:14:03 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
15.08 16:14:03 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
15.08 16:14:03 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
15.08 16:14:03 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
15.08 16:14:03 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
15.08 16:14:03 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
15.08 16:14:03 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
15.08 16:14:03 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
15.08 16:14:03 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
15.08 16:14:03 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
15.08 16:14:03 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'marry' in plugin Marriage v2.0.17
15.08 16:14:03 [Server] ERROR null
15.08 16:14:03 [Server] INFO Sir_CLASH issued server command: /marry Test

**Comment by SirCLASH** [comment]
Now, in Version 2.0.17 - Got this problem:

Errors are away, but:

when typing:
/marry PLAYER - it says: not enough arguments

when typing:
/marry marry PLAYER - it says: Player marry was not found

when typing:
/marry PLAYER1 PLAYER2 - it says: you cant marry 2 players

So its totally impossible to marry any player. 
Tried all permissions.

**Comment by lenis0012** [comment]
@SirCLASH that's weird.
Ill look into it
