### ISSUE TITLE
Marriage DB

### ISSUE THREAD

**Issue by AmazedMender16** [lenis0012/Marriage#33]
Whenever you put ?useSSL=false& behind the DB name it wont be able to find it..

Hope u can come with a fix

**Comment by lenis0012** [comment]
@AmazedMender16 I will look into adding an option for aditional parameters.
if that is unlogical, i will add ssl support with a flag.

thanks for informing me

**Comment by lenis0012** [comment]
Fixed in latest dev-build.
http://ci.lenis0012.com/job/Marriage/

You should now be able to append ?useSSL=false behind the DB name
If the issue persists, let me know.

**Comment by AmazedMender16** [comment]
Seems to work dude! appreciated
