### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by En0tS** [lenis0012/Marriage#39]
Hi! Please add /marry kiss command as an alternative for crouch and click.
And very needed translatable /marry list

**Comment by En0tS** [comment]
Also will be useful to add price for gender changing.

**Comment by baxandrei** [comment]
I wanted to propose the same thing. I have a trading plugin that works on the same mechanics and these plugins don't quite understand each other.

**Comment by baxandrei** [comment]
Also, it would be useful for /marry gift command to check if your partner has the full inventory or not, because you are going to send gifts even if it is full and thus the items are lost.

**Comment by lenis0012** [comment]
@BaxAndrei in the new update, the full inventory check is being performed.

As for a paid gift command, I will add optional support for it.
I am also planning to add a gift shop in one of the future updates.

**Comment by lenis0012** [comment]
Going to close this issue
