### ISSUE TITLE
ci.lenis0012.com Down

### ISSUE THREAD

**Issue by SpencerSharkey** [lenis0012/Marriage#41]
It appears the maven repo at http://ci.lenis0012.com/ is down, with a 502 Bad Gateway error.

This is preventing me from building this plugin from source.

**Comment by lenis0012** [comment]
@SpencerSharkey Sorry for my very late reply.
We have moved to https://ci.codemc.io/

**Comment by alfie1706** [comment]
It appears you haven't moved all of your repositories over to codemc.io?

**Comment by lenis0012** [comment]
https://ci.codemc.io/job/lenis0012/job/Marriage/
