### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by QueenAngus** [lenis0012/Marriage#42]
hi there,

marriage gives me the following error in console on startup:

https://pastebin.com/21wWf7Ck

any reason why? ty

**Comment by TheFlagCourier** [comment]
Yeah, the PlotSquared copy bundled in the repo and used as a dependency is out-of-date. Only legacy versions of PlotSquared may work with this as it stands. (I could only garuntee it would work using the PlotSquared jarfile in this repo's libs directory.)

Got a PR that would fix this issue.

**Comment by lenis0012** [comment]
Should be fixed in the new dev build
https://ci.codemc.io/job/lenis0012/job/Marriage/
