### ISSUE TITLE
Player was not in cache

### ISSUE THREAD

**Issue by Metphrip** [lenis0012/Marriage#45]
Please help me solve this problem.
`[Marriage] Player Metphrip was not in cache, and will be loaded on the main thread.`
Many functions do not work with this problem, such as teleport, online check, etc.
I use this plugin on "Nukkit"
Thank you very much in advance

**Comment by lenis0012** [comment]
This warning is logged when the AsyncPlayerPreLoginEvent is not executed before the PlayerJoinEvent.

this means that the player cannot be loaded asynchronously, and this will result in a loss of performance.

It is an issue that Nukkit should probably fix.
As for the other issues you are experiencing, again these are likely issues in Nukkit's implementation of Bukkit.

I don't know to what extend these issues are fixable.

**Comment by lenis0012** [comment]
Going to close this due to inactivity. Feel free to open a new issue.
