### ISSUE TITLE
SSL error in console

### ISSUE THREAD

**Issue by MaxIsV** [lenis0012/Marriage#52]
Hello, lately I am often getting SSL errors in the console when a player logs in or out. The marriage plugin is mentioned there, so I think the problem is related to it. It is a pity that I myself cannot disable the SSL option in the config.

Server core: paper-1.12.2
Marriage-2.0.19
Error: https://pastebin.com/YFSczvFs

**Comment by lenis0012** [comment]
Fix in version 2.1.2 using new "ssl" property in database-settings.yml
