### ISSUE TITLE
[Request] /marry help

### ISSUE THREAD

**Issue by iTaeyeonKim** [lenis0012/Marriage#55]
Hello.

I just wanted to ask you to add an option so we can edit /marry help

I don't want certain things to show up on this list. Can't find a way to do it.

For example, I don't want players to choose gender or send gift, but in /marry help that will be displayed anyway.

Thanks and have a nice day/night! :)

**Comment by lenis0012** [comment]
You can add 'gender' to the "disabled-commands" setting in your config.yml
