### ISSUE TITLE
New updated for valentine's and new errors FIX IT

### ISSUE THREAD

**Issue by LemonSen** [lenis0012/Marriage#60]
There new update on occasion of valentine's day 2.2.0 and its creates a new bug /error FIX IT SOON
![image](https://user-images.githubusercontent.com/125338991/218648513-795b965d-ad4d-4f34-bcd0-eaf95083a09f.png)
![image](https://user-images.githubusercontent.com/125338991/218648533-48a0c6c2-6c7c-4865-b6a0-920700565df8.png)

**Comment by lenis0012** [comment]
Thank you for reporting. I will fix this issue immediately.
