### ISSUE TITLE
Another new problem hahah idk what did you fixed mate

### ISSUE THREAD

**Issue by LemonSen** [lenis0012/Marriage#61]
[message (2).txt](https://github.com/lenis0012/Marriage/files/10730742/message.2.txt)

**Comment by lenis0012** [comment]
I am so sorry. I did not have the ability to test the 2.2.1 version because I don't have access to a server at the moment.
I will fix the issue in a few hours when I have some time.

**Comment by LemonSen** [comment]
Ok sure take your time

**Comment by lenis0012** [comment]
Sorry. I had very little time and wanted to release an update hoping it would fix the issue. I will make sure to double check the next version I release.

**Comment by LemonSen** [comment]
Thank you but if it still cause the error amma report again hahah anyways have a great day
