### ISSUE TITLE
Feature Request: Make married players list's message configurable

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [lenis0012/Marriage#62]
It would be nice if
![image](https://user-images.githubusercontent.com/45261195/218764063-1aac475f-7518-492f-9af2-e6cb48d141e5.png)
in /marry list is configurable in messages.yml

And also, It would be nice if the default green in /marry list is able to change to other colors
![image](https://user-images.githubusercontent.com/45261195/218764426-a2291ca3-c9bf-474d-ab55-37f94650c1b0.png)

**Comment by lenis0012** [comment]
You are right, these changes would be nice to have. I will look in to it.

**Comment by lenis0012** [comment]
@Aira-Sakuranomiya This should be possible in the latest version. Let me know if you experience any issues.

**Comment by Aira-Sakuranomiya** [comment]
Works perfectly. Thank you so much!!!
