### ISSUE TITLE
Another one broo idk whats happening 

### ISSUE THREAD

**Issue by LemonSen** [lenis0012/Marriage#63]
![Screenshot_20230215-161658_Discord](https://user-images.githubusercontent.com/125338991/219006966-4029603c-2eb9-4349-b013-c47893843d4c.jpg)

**Comment by lenis0012** [comment]
Hmm. This issue is completely unrelated. Still very unfortunate though.

Could you try the latest dev build? https://ci.codemc.io/job/lenis0012/job/Marriage/60/

This issue is related to a change I made for SqLite, i reverted it to the original behavior in build 60
