### ISSUE TITLE
Gender update is not real-time

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [lenis0012/Marriage#67]
Version: 2.3.0
Server: Latest Paper (paper-1.19.3-442)

I set my gender to from one to another.
And I issued `/marry list` I discovered my gender isn't updated. It didn't update real-time in the database too.

No error or warning in the log, it just didn't update real-time.

**Comment by lenis0012** [comment]
Please try with the latest dev build and open a new issue if you experience further issues.
